spring.application.name=Kasper_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/kasperDB
spring.datasource.username=postgres
spring.datasource.password=151651

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=3600000
